In [74]:
import pandas as pd

In [75]:
PATH = "asteroid.csv"

In [76]:
df = pd.read_csv(PATH)

C:\Users\ponts\AppData\Local\Temp\ipykernel_14548\3476328945.py:1: DtypeWarning: Columns (0: pdes, 1: name, 2: prefix) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(PATH)

In [77]:
df.head()

,id,spkid,full_name,pdes,name,prefix,neo,pha,H,diameter,...,sigma_i,sigma_om,sigma_w,sigma_ma,sigma_ad,sigma_n,sigma_tp,sigma_per,class,rms
0,a0000001,2000001,1 Ceres,1,Ceres,NaN,N,N,3.40,939.400,...,4.608900e-09,6.168800e-08,6.624800e-08,7.820700e-09,1.111300e-11,1.196500e-12,3.782900e-08,9.415900e-09,MBA,0.43301
1,a0000002,2000002,2 Pallas,2,Pallas,NaN,N,N,4.20,545.000,...,3.469400e-06,6.272400e-06,9.128200e-06,8.859100e-06,4.961300e-09,4.653600e-10,4.078700e-05,3.680700e-06,MBA,0.35936
2,a0000003,2000003,3 Juno,3,Juno,NaN,N,N,5.33,246.596,...,3.223100e-06,1.664600e-05,1.772100e-05,8.110400e-06,4.363900e-09,4.413400e-10,3.528800e-05,3.107200e-06,MBA,0.33848
3,a0000004,2000004,4 Vesta,4,Vesta,NaN,N,N,3.00,525.400,...,2.170600e-07,3.880800e-07,1.789300e-07,1.206800e-06,1.648600e-09,2.612500e-10,4.103700e-06,1.274900e-06,MBA,0.39980
4,a0000005,2000005,5 Astraea,5,Astraea,NaN,N,N,6.90,106.699,...,2.740800e-06,2.894900e-05,2.984200e-05,8.303800e-06,4.729000e-09,5.522700e-10,3.474300e-05,3.490500e-06,MBA,0.52191

In [78]:
print(df.shape)

(958524, 45)

In [79]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
id                     0
spkid                  0
full_name              0
pdes                   0
name              936460
prefix            958506
neo                    4
pha                19921
H                   6263
diameter          822315
albedo            823421
diameter_sigma    822443
orbit_id               0
epoch                  0
epoch_mjd              0
epoch_cal              0
equinox                0
e                      0
a                      0
q                      0
i                      0
om                     0
w                      0
ma                     1
ad                     4
n                      0
tp                     0
tp_cal                 0
per                    4
per_y                  1
moid               19921
moid_ld              127
sigma_e            19922
sigma_a            19922
sigma_q            19922
sigma_i            19922
sigma_om           19922
sigma_w            19922
sigma_ma           19922
sigma_ad           19926
sigma_n            19922
sigma_tp           19922
sigma_per          19926
class                  0
rms                    2
dtype: int64

In [80]:
print("Duplicate rows in the dataset:", df.duplicated().sum())

Duplicate rows in the dataset: 0

In [81]:
# Remove rows with ANY NaN values
df_no_nulls = df.dropna()

In [82]:
print("Dataset shape after removing rows with NaN values:", df_no_nulls.isnull().sum())
print("Dataset shape after removing rows with NaN values:", df_no_nulls.shape)

Dataset shape after removing rows with NaN values: id                0
spkid             0
full_name         0
pdes              0
name              0
prefix            0
neo               0
pha               0
H                 0
diameter          0
albedo            0
diameter_sigma    0
orbit_id          0
epoch             0
epoch_mjd         0
epoch_cal         0
equinox           0
e                 0
a                 0
q                 0
i                 0
om                0
w                 0
ma                0
ad                0
n                 0
tp                0
tp_cal            0
per               0
per_y             0
moid              0
moid_ld           0
sigma_e           0
sigma_a           0
sigma_q           0
sigma_i           0
sigma_om          0
sigma_w           0
sigma_ma          0
sigma_ad          0
sigma_n           0
sigma_tp          0
sigma_per         0
class             0
rms               0
dtype: int64
Dataset shape after removing rows with NaN values: (0, 45)

In [83]:
df_no_nulls.head()

Empty DataFrame
Columns: [id, spkid, full_name, pdes, name, prefix, neo, pha, H, diameter, albedo, diameter_sigma, orbit_id, epoch, epoch_mjd, epoch_cal, equinox, e, a, q, i, om, w, ma, ad, n, tp, tp_cal, per, per_y, moid, moid_ld, sigma_e, sigma_a, sigma_q, sigma_i, sigma_om, sigma_w, sigma_ma, sigma_ad, sigma_n, sigma_tp, sigma_per, class, rms]
Index: []

[0 rows x 45 columns]

- Dropping rows by searching for null rows removes every entry

- Since my main focus on the diameter of Asteroids, missing asteroid data will only hinder my research
    - So i will remove rows with missing diameters

In [84]:
df_no_diameter_nulls = df.dropna(subset=['diameter'])

In [85]:
df_no_diameter_nulls.head()

,id,spkid,full_name,pdes,name,prefix,neo,pha,H,diameter,...,sigma_i,sigma_om,sigma_w,sigma_ma,sigma_ad,sigma_n,sigma_tp,sigma_per,class,rms
0,a0000001,2000001,1 Ceres,1,Ceres,NaN,N,N,3.40,939.400,...,4.608900e-09,6.168800e-08,6.624800e-08,7.820700e-09,1.111300e-11,1.196500e-12,3.782900e-08,9.415900e-09,MBA,0.43301
1,a0000002,2000002,2 Pallas,2,Pallas,NaN,N,N,4.20,545.000,...,3.469400e-06,6.272400e-06,9.128200e-06,8.859100e-06,4.961300e-09,4.653600e-10,4.078700e-05,3.680700e-06,MBA,0.35936
2,a0000003,2000003,3 Juno,3,Juno,NaN,N,N,5.33,246.596,...,3.223100e-06,1.664600e-05,1.772100e-05,8.110400e-06,4.363900e-09,4.413400e-10,3.528800e-05,3.107200e-06,MBA,0.33848
3,a0000004,2000004,4 Vesta,4,Vesta,NaN,N,N,3.00,525.400,...,2.170600e-07,3.880800e-07,1.789300e-07,1.206800e-06,1.648600e-09,2.612500e-10,4.103700e-06,1.274900e-06,MBA,0.39980
4,a0000005,2000005,5 Astraea,5,Astraea,NaN,N,N,6.90,106.699,...,2.740800e-06,2.894900e-05,2.984200e-05,8.303800e-06,4.729000e-09,5.522700e-10,3.474300e-05,3.490500e-06,MBA,0.52191

In [87]:
print("Dataset shape after removing rows with NaN values:", df_no_diameter_nulls.isnull().sum())

Dataset shape after removing rows with NaN values: id                     0
spkid                  0
full_name              0
pdes                   0
name              121047
prefix            136209
neo                    0
pha                    0
H                   4164
diameter               0
albedo              1109
diameter_sigma       128
orbit_id               0
epoch                  0
epoch_mjd              0
epoch_cal              0
equinox                0
e                      0
a                      0
q                      0
i                      0
om                     0
w                      0
ma                     0
ad                     0
n                      0
tp                     0
tp_cal                 0
per                    0
per_y                  0
moid                   0
moid_ld                0
sigma_e                0
sigma_a                0
sigma_q                0
sigma_i                0
sigma_om               0
sigma_w                0
sigma_ma               0
sigma_ad               0
sigma_n                0
sigma_tp               0
sigma_per              0
class                  0
rms                    0
dtype: int64

In [ ]:
df_no_diameter_nulls.tail()

,id,spkid,full_name,pdes,name,prefix,neo,pha,H,diameter,...,sigma_i,sigma_om,sigma_w,sigma_ma,sigma_ad,sigma_n,sigma_tp,sigma_per,class,rms
891841,bK16N24W,3755298,(2016 NW24),2016 NW24,NaN,NaN,N,N,17.4,2.696,...,0.000018,0.000154,0.003027,0.003327,1.472800e-06,1.949700e-07,0.014136,0.001199,MBA,0.42754
891971,bK16N35R,3755382,(2016 NR35),2016 NR35,NaN,NaN,N,N,16.8,2.917,...,0.000016,0.000029,0.000047,0.000040,4.150600e-07,2.865100e-08,0.000315,0.000330,MBA,0.58054
894103,bK16P66B,3757444,(2016 PB66),2016 PB66,NaN,NaN,N,N,17.2,3.271,...,0.000067,0.000116,0.001493,0.000588,2.269800e-06,1.603500e-07,0.002675,0.001686,MBA,0.53016
901055,bK16TB9F,54000016,(2016 TF119),2016 TF119,NaN,NaN,N,N,16.0,3.009,...,0.000034,0.000025,0.000331,0.000086,9.530100e-07,6.243600e-08,0.000327,0.000752,MBA,0.57294
909489,bK17B98V,3768324,(2017 BV98),2017 BV98,NaN,NaN,N,N,18.3,1.600,...,0.000012,0.000138,0.000158,0.000104,8.802300e-08,1.290800e-08,0.000411,0.000068,MBA,0.75791

- Dataframe is now free of Null diameters.